// React/WebGame/4.반응속도체크/ResponseCheck.jsx
import React, { Component } from 'react';

class ResponseCheck extends Component {

    state = {
        state: 'waiting',
        message: '클릭해서 시작하세요',
        result: [],

    };

    timeout;
    startTime;
    endTime;


    onClickScreen = () => {
        const { state, message, result } = this.state;
        if (state === 'waiting') {
            this.setState({
                state: 'ready',
                message: '초록색이 되면 클릭하세요',
            })
            this.timeout = setTimeout(() => {
                this.setState({
                    state: 'now',
                    message: '지금 클릭',
                })
                this.startTime = new Date();
            }, Math.floor(Math.random() * 1000) + 2000)
        } else if (state === 'ready') {
            this.setState({
                state: 'waiting',
                message: '성급하셨군요 초록색이 된 후에 클릭하세요',
            })
            clearTimeout(this.timeout);
        } else if (state === 'now') {
            this.endTime = new Date();
            this.setState((prevState) => {
                return {
                    state: 'waiting',
                    message: '클릭해서 시작하세요',
                    result: [...prevState.result, this.endTime - this.startTime],
                }
            })
        }

    }

    render() {
        return (
            <>
                <div
                    id="screen"
                    className={this.state.state}
                    onClick={this.onClickScreen}>
                    {this.state.message}
                </div>
                {this.state.result.length === 0
                    ? null
                    : <div>평균 시간 :{this.state.result.reduce((a, c) => a + c) / this.state.result.length}ms</div>
                }
            </>
        )
    };
}


export default ResponseCheck;

// Vue/4.반응속도체크/ResponseCheck.vue

<template>
    <div>
        <div id="screen"  v-bind:class = "state" @click="onClickScreen">{{message}}</div>
        <div v-show="result.length">
            <div>평균 시간: {{ average || 0}}ms</div>
            <button @click="onReset">리셋</button>
        </div>
    </div>
</template>

<script>
    let startTime = 0;
    let endTime = 0;
    let timeout = null;
    export default{
        data(){
            return{
                result:[],
                state: 'waiting',
                message:'클릭해서 시작하세요.',
            }
        },
        computed:{
            average(){
                return this.result.reduce((a,c)=>a+c,0)/this.result.length
            }
        },
        methods :{
            onReset(){
                this.result = [];
            },
            onClickScreen(){
                if (this.state === 'waiting'){
                    this.state = 'ready';
                    this.message = '초록색이 되면 클릭하세요';
                    timeout = setTimeout(()=>{
                        this.state = 'now';
                        this.message = '지금 클릭!';
                        startTime = new Date();
                    },Math.floor(Math.random()*1000)+2000);
                }else if(this.state === 'ready'){
                    clearTimeout(timeout);
                    this.state = 'waiting';    
                    this.message = '너무 성급하시군요! 초록색이 된 후에 클릭하세요.'
                }else if(this.state === 'now'){
                    endTime = new Date();
                    this.state = 'waiting';
                    this.message = '클릭해서 시작하세요.' ; 
                    this.result.push(endTime-startTime);
                }
            },
        }
    }
</script>

<style scoped>
    #screen{
        width: 300px;
        height: 200px;
        text-align: center;
        user-select:none;
    }
    #screen.waiting{
        background-color: aqua;
    }
    #screen.ready{
        background-color: red;
        color : white;
    }
    #screen.now{
        background-color: greenyellow;
    }
</style>
